import Foundation
import SwiftUI

struct Info {
    let title: String
    let image: String
    let backgroundImage1: String
    let name: String
    let story: String
    let hobbies: [String]
    let foods: [String]
    let colors: [Color]
    let funFacts: [String]

}

let information = Info(
    title: "iOS Dev",
    image: "ChatGPT03",
    backgroundImage1: "binary-code",
    name: "Jose Marquez",
    story: "Ever since I discovered a beige PC humming under a CRT at Radioshack in the mid 90s, I've been fascinated by how bits become experiences. I learned to defrag hard drives, set jumpers, and survive the screech of dial-up. I installed shareware from CD-ROMs, typed commands into MS-DOS, and watched pixels bloom on 256-color screens.\n\nThen I met Slackware Linux. Floppy installs, kernel configs, and a window manager that felt like the future: Enlightenment. I learned what a runlevel was, compiled my first kernel, and tweaked themes until every shadow and bevel felt just right. X started up with that satisfying flicker, and suddenly the desktop was mine to shape.\n\nI spent nights exploring FTP mirrors and dialing into BBSs with a US Robotics 56k modem—the handshake chorus still lives in my head. I traded tips, scripts, and shareware, and watched download bars crawl while reading readme files like novels.\n\nAt school and labs I discovered SGI workstations running IRIX. Indigo and Octane boxes glowed like artifacts from another timeline. On them, I saw Alias|Wavefront Maya and StudioTools in motion—splines, NURBS, and render passes that made my jaw drop. The marriage of art and math felt like magic, and I chased that feeling into every tool I could find.\n\nIn the 2000s I built my first PC from parts: an ATX case, a rattling 80mm fan, and a GPU that needed a Molex adapter. I broke things, flashed BIOSes, and learned to read schematics at 2 a.m. Open-source communities taught me to ask better questions and give back better answers.\n\nToday I tinker with single-board computers, containers, and on-device ML. I care about privacy, performance, and the craft of making software that respects users. I still love the smell of warm solder and the thrill of a clean boot after a risky change.\n\nWhen I'm not debugging, I'm exploring retro hardware and preserving the stories behind it—because the future makes more sense when you can feel the weight of a clicky keyboard and hear a floppy spin up.\n\n ",
    hobbies: ["bicycle", "ticket.fill", "book.fill"],
    foods: ["🥐", "🌮", "🍣"],
    colors: [Color.blue, Color.purple, Color.pink],
    funFacts: [
        "Bananas are berries, but strawberries are not.",
        "Octopuses have three hearts and blue blood.",
        "A group of flamingos is called a flamboyance.",
        "Honey never spoils and can last for thousands of years.",
        "Wombats produce cube-shaped poop.",
        "Sharks existed before trees.",
        "The Eiffel Tower can grow taller in summer due to heat expansion.",
        "Sloths can hold their breath longer than dolphins can.",
        "The inventor of the microwave discovered it after a candy bar melted in his pocket.",
        "There are more stars in the universe than grains of sand on Earth.",
        "Cows have best friends and get stressed when separated.",
        "An apple floats because it is about 25% air.",
        "The shortest war in history lasted 38 minutes.",
        "A day on Venus is longer than a year on Venus.",
        "Sea otters hold hands while sleeping so they do not drift apart.",
        "Some turtles can breathe through their butts.",
        "The dot over a lowercase i or j is called a tittle.",
        "Scotland’s national animal is the unicorn.",
        "A bolt of lightning is five times hotter than the surface of the sun.",
        "Pineapples take about two years to grow.",
        "Koalas have fingerprints almost identical to humans.",
        "The human nose can remember over 50,000 different scents.",
        "Butterflies can taste with their feet.",
        "A cloud can weigh more than a million pounds.",
        "The first oranges were actually green.",
        "Rabbits cannot vomit.",
        "The Moon has moonquakes.",
        "Dolphins have names for each other using unique whistles.",
        "The hashtag symbol is technically called an octothorpe.",
        "Mantis shrimp can punch with the speed of a bullet.",
        "Humans share about 60% of their DNA with bananas.",
        "There are more fake flamingos in the world than real ones.",
        "Some cats are allergic to humans.",
        "The inventor of the Frisbee was turned into a Frisbee after he died.",
        "A snail can sleep for up to three years.",
        "The heart of a blue whale is so large a human could swim through its arteries.",
        "The average person walks the equivalent of five times around Earth in a lifetime.",
        "Hot water can freeze faster than cold water under certain conditions.",
        "The longest English word without a vowel is rhythm.",
        "A shrimp’s heart is located in its head.",
        "Tigers have striped skin, not just striped fur.",
        "A single strand of spaghetti is called a spaghetto.",
        "The inventor of the Pringles can is buried in one.",
        "A crocodile cannot stick its tongue out.",
        "There is enough gold in Earth’s core to coat the planet’s surface.",
        "Owls do not have eyeballs; they have eye tubes.",
        "The first computer mouse was made of wood.",
        "Ants do not have lungs.",
        "The world’s oldest known pet cat existed 9,500 years ago.",
        "Some frogs can freeze solid and survive.",
        "The unicorn is the national animal of Scotland.",
        "A chef’s hat traditionally has 100 folds.",
        "Jellyfish have existed longer than dinosaurs.",
        "A group of crows is called a murder.",
        "The fingerprints of a koala can confuse crime scene investigators.",
        "Mosquitoes are attracted to the color blue twice as much as any other color.",
        "You cannot hum while holding your nose shut.",
        "The tiny pocket in jeans was originally designed for pocket watches.",
        "A giraffe’s tongue can be over 18 inches long.",
        "The longest hiccuping spree lasted 68 years.",
        "The word nerd was first coined by Dr. Seuss.",
        "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
        "Penguins propose to mates with pebbles.",
        "Bamboo is technically a grass.",
        "The average cloud weighs about 1.1 million pounds.",
        "Some metals are so reactive they explode in water.",
        "The first alarm clock could only ring at 4 a.m.",
        "A duck’s quack does echo, despite the myth.",
        "The Twitter bird’s official name is Larry.",
        "The inventor of LEGO was a carpenter.",
        "A baby puffin is called a puffling.",
        "Your stomach gets a new lining every few days.",
        "The longest recorded flight of a chicken is 13 seconds.",
        "Water can boil and freeze at the same time.",
        "A group of porcupines is called a prickle.",
        "The Earth is not perfectly round; it bulges at the equator.",
        "The sentence 'The quick brown fox jumps over the lazy dog' contains every letter in the English alphabet.",
        "A cow-bison hybrid is called a beefalo.",
        "The first oranges were grown in Southeast Asia.",
        "Humans glow in the dark, but the light is too faint to see.",
        "Some sea snakes can breathe through their skin.",
        "The inventor of the Super Soaker was a NASA engineer.",
        "A day on Mercury lasts about 59 Earth days.",
        "Pigeons can recognize themselves in mirrors.",
        "The average raindrop falls at about 14 miles per hour.",
        "The human brain uses enough electricity to power a small light bulb.",
        "A bolt of lightning can travel up to 60,000 miles per second.",
        "There are more possible chess games than atoms in the observable universe.",
        "The fear of long words is called hippopotomonstrosesquipedaliophobia.",
        "Sea cucumbers fight by shooting out their internal organs.",
        "The shortest complete sentence in English is 'I am.'",
        "A cat can jump up to six times its body length.",
        "Some turtles glow in the dark under ultraviolet light.",
        "The world’s largest desert is Antarctica.",
        "The first video uploaded to YouTube was only 18 seconds long.",
        "An ostrich’s eye is bigger than its brain.",
        "Bubble wrap was originally invented as wallpaper.",
        "The average person spends about six months of their lifetime waiting at red lights.",
        "Bees can recognize human faces.",
        "There is a species of jellyfish that can technically live forever.",
        "The inventor of Velcro was inspired by burrs sticking to his dog.",
        "The sound of cracking knuckles comes from bubbles bursting in joint fluid.",
        "A watermelon is about 92% water."
      ]

)

